services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5000:5173

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
