services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5000:5173
